### ISSUE TITLE
How use with http://www.freecodecamp.com/

### ISSUE THREAD

**Issue by xavierartot** [NickTomlin/pocketvim#5]
Hi,
I'm trying to use with http://www.freecodecamp.com/
It works but only when I disable Vimuim
thank you

**Comment by NickTomlin** [comment]
Interesting, I can't get it to work at all :)  I'll investigate, thanks for bringing this up!

**Comment by xavierartot** [comment]
That can be really coll

**Comment by xavierartot** [comment]
I post a message about that in Reddit:
https://www.reddit.com/r/vim/comments/3xhy0h/how_use_vim_with_chrome_in_a_div/

**Comment by ClaudeDev** [comment]
I am trying to get it work in freeCodeCamp too, 
if you get around, it would be great

**Comment by xavierartot** [comment]
I gave up and I coding in Vim, then copy/paste.
